library(graph4lg)
library(rethinking)
library(SimMultiCorrData)
library(MASS)
library(caret)
library(Boruta)
library(FSelectorRcpp)
library(FSinR)
library(sparseSVM)
library(BiocManager)
BiocManager::install(version ='3.16')
BiocManager::install("FCBF", version="devel")
library(FCBF)
