library(rethinking)
library(MASS)
library(data.table)
library(copula)
library(caret)
library(stir)
library(Boruta)
library(FSelectorRcpp)
library(FSinR)
library(sparseSVM)
#remotes::install_github("insilico/STIR")
#library(BiocManager)
##BiocManager::install(version ='3.16')
#BiocManager::install("FCBF")
#library(FCBF)
library(Biocomb)

